# Generated by Django 2.1.4 on 2019-07-12 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('checkin_time', models.TimeField(blank=True, default=datetime.time(11, 57, 58, 149778), null=True)),
                ('bed', models.CharField(blank=True, max_length=30)),
                ('phone', models.BigIntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('manager', models.CharField(blank=True, max_length=30)),
                ('present', models.BooleanField(default=False)),
                ('checkout_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('checkout_time', models.TimeField(blank=True, default=datetime.time(11, 57, 58, 150298), null=True)),
            ],
        ),
    ]
