# Generated by Django 2.2.3 on 2019-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(null=True)),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('bed', models.CharField(blank=True, max_length=30)),
                ('phone', models.BigIntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('present', models.BooleanField(default=False)),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('invoice', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('day_price', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('manager', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
