# Generated by Django 2.2.3 on 2019-07-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='days',
            new_name='day',
        ),
    ]
