# Generated by Django 2.1.4 on 2019-06-02 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='time',
        ),
        migrations.AddField(
            model_name='customer',
            name='checkin_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='checkin_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 3, 44, 155152), null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='checkout_date',
            field=models.TimeField(blank=True, default=datetime.time(8, 3, 44, 155269), null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='checkout_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 3, 44, 155290), null=True),
        ),
    ]
