# Generated by Django 2.2.3 on 2019-07-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190714_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='day',
        ),
        migrations.AddField(
            model_name='customer',
            name='duration',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
