# Generated by Django 2.2.3 on 2019-07-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190713_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='maanger',
        ),
        migrations.AlterField(
            model_name='customer',
            name='manager',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
