# Generated by Django 2.2.2 on 2019-06-17 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190617_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkin_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 5, 36, 768358), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkout_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 6, 17, 10, 5, 36, 768425), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkout_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 5, 36, 768434), null=True),
        ),
    ]
