# Generated by Django 2.2.3 on 2019-07-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_customer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='duration',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
