# Generated by Django 2.2.2 on 2019-06-17 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190617_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkin_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 6, 17, 10, 7, 22, 95663), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkin_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 7, 22, 95687), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkout_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 6, 17, 10, 7, 22, 95747), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkout_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 7, 22, 95756), null=True),
        ),
    ]
