# Generated by Django 2.2.2 on 2019-06-17 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190617_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkin_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 6, 17, 10, 7, 28, 60735), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkin_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 7, 28, 60758), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkout_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 6, 17, 10, 7, 28, 60825), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkout_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 7, 28, 60835), null=True),
        ),
    ]
