# Generated by Django 2.2.2 on 2019-06-17 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20190617_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkin_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 9, 39, 742624), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkout_time',
            field=models.TimeField(blank=True, default=datetime.time(10, 9, 39, 742700), null=True),
        ),
    ]
